name = "Cobweb"
uuid = "ec354790-cf28-43e8-bb59-b484409b7bad"
authors = ["joshday <emailjoshday@gmail.com> and contributors"]
version = "0.2.3"

[deps]
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
DefaultApplication = "1"
Scratch = "1.1"
StructTypes = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
